In [12]:
data = [
    {'price': 850, 'rooms': 4, 'neighborhood': 'Queen Anne'},
     {'price': 650, 'rooms': 3, 'neighborhood': 'Queen Anne'},
     {'price': 700, 'rooms': 1, 'neighborhood': 'Wallingford'},
     {'price': 650, 'rooms': 3, 'neighborhood': 'Wallingford'},
     {'price': 700, 'rooms': 3, 'neighborhood': 'Fremont'},
    {'price': 600, 'rooms': 2, 'neighborhood': 'Fremont'}
]
data

[{'price': 850, 'rooms': 4, 'neighborhood': 'Queen Anne'},
 {'price': 650, 'rooms': 3, 'neighborhood': 'Queen Anne'},
 {'price': 700, 'rooms': 1, 'neighborhood': 'Wallingford'},
 {'price': 650, 'rooms': 3, 'neighborhood': 'Wallingford'},
 {'price': 700, 'rooms': 3, 'neighborhood': 'Fremont'},
 {'price': 600, 'rooms': 2, 'neighborhood': 'Fremont'}]

In [18]:
import pandas as pd    
from statsmodels.formula.api import ols as sm_ols
print('The coefs from SM:')
print(sm_ols('price ~ neighborhood - 1', data = pd.DataFrame(data)).fit().params)
# ""-1" means no intercept. Don't do this! It's here for illustration

The coefs from SM:
neighborhood[Fremont]        650.0
neighborhood[Queen Anne]     750.0
neighborhood[Wallingford]    675.0
dtype: float64


In [16]:
#Maybe we do this

In [17]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer(sparse = False, dtype = int)

data2 = vec.fit_transform(data) #vec with ".fit_transform", save to new data obj
print(data2, '\n')
print(vec.get_feature_names()) #can use .get_feature_names() to recover names


from sklearn.linear_model import LinearRegression
print('Reg coefs:')
LinearRegression(fit_intercept = False).fit(data2[:,:3], data2[:,3]).coef_

[[  0   1   0 850   4]
 [  0   1   0 650   3]
 [  0   0   1 700   1]
 [  0   0   1 650   3]
 [  1   0   0 700   3]
 [  1   0   0 600   2]] 

['neighborhood=Fremont', 'neighborhood=Queen Anne', 'neighborhood=Wallingford', 'price', 'rooms']
Reg coefs:


array([650., 750., 675.])

In [33]:
import pandas as pd
import numpy as np
import seaborn as sns
from statsmodels.formula.api import ols as sm_ols
from statsmodels.iolib.summary2 import summary_col
import datetime as dt

In [34]:
url = 'https://github.com/LeDataSciFi/lectures-spr2020/blob/master/assignment_data/Fannie_Mae_Plus_Data.gzip?raw=true'
fannie_mae = pd.read_csv(url,compression='gzip')  
print(fannie_mae.info())
pd.options.display.float_format = '{:,.1f}'.format
fannie_mae.drop('Loan_Identifier',axis=1).describe().round(1).transpose()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135038 entries, 0 to 135037
Data columns (total 36 columns):
Loan_Identifier                            135038 non-null float64
Origination_Channel                        135038 non-null object
Seller_Name                                135038 non-null object
Original_Interest_Rate                     135038 non-null float64
Original_UPB                               135038 non-null float64
Original_Loan_Term                         135038 non-null float64
Original_LTV_(OLTV)                        135038 non-null float64
Original_Combined_LTV_(CLTV)               134007 non-null float64
Number_of_Borrowers                        135007 non-null float64
Original_Debt_to_Income_Ratio              132396 non-null float64
Borrower_Credit_Score_at_Origination       134481 non-null float64
Loan_purpose                               135038 non-null object
Property_type                              135038 non-null object
Number_of_units       

count      mean       std  \
Original_Interest_Rate                  135,038.0       5.2       1.3   
Original_UPB                            135,038.0 188,931.1 108,742.4   
Original_Loan_Term                      135,038.0     307.1      82.3   
Original_LTV_(OLTV)                     135,038.0      70.1      17.5   
Original_Combined_LTV_(CLTV)            134,007.0      70.9      17.6   
Number_of_Borrowers                     135,007.0       1.6       0.5   
Original_Debt_to_Income_Ratio           132,396.0      33.3      11.5   
Borrower_Credit_Score_at_Origination    134,481.0     742.4      53.4   
Number_of_units                         135,038.0       1.0       0.2   
Zip_code_short                          135,038.0     546.0     306.0   
Primary_mortgage_insurance_percent       24,322.0      23.8       7.2   
Co-borrower_credit_score_at_origination  67,366.0     751.1      50.6   
Mortgage_Insurance_type                  24,322.0       1.1       0.3   
UNRATE                                  135,038.0       6.2       1.7   
CPIAUCSL                                135,038.0     208.2      24.8   
rGDP                                    135,038.0       2.1       2.3   
TCMR                                    135,038.0       3.5       1.2   
POILWTIUSDM                             135,038.0      56.3      27.8   
TTLCONS                                 135,038.0 963,119.3 153,846.4   
DEXUSEU                                 135,038.0       1.2       0.2   
BOPGSTB                                 135,038.0 -42,336.6   9,404.5   
GOLDAMGBD228NLBM                        135,038.0     845.9     498.1   
CSUSHPISA                               135,038.0     148.6      24.7   
MSPUS                                   135,038.0 231,137.7  46,186.1   

                                              min       25%       50%  \
Original_Interest_Rate                        2.2       4.2       5.2   
Original_UPB                              8,000.0 108,000.0 164,000.0   
Original_Loan_Term                           60.0     240.0     360.0   
Original_LTV_(OLTV)                           4.0      60.0      75.0   
Original_Combined_LTV_(CLTV)                  4.0      61.0      75.0   
Number_of_Borrowers                           1.0       1.0       2.0   
Original_Debt_to_Income_Ratio                 1.0      25.0      33.0   
Borrower_Credit_Score_at_Origination        361.0     707.0     755.0   
Number_of_units                               1.0       1.0       1.0   
Zip_code_short                                0.0     295.0     549.0   
Primary_mortgage_insurance_percent            6.0      18.0      25.0   
Co-borrower_credit_score_at_origination     400.0     721.0     765.0   
Mortgage_Insurance_type                       1.0       1.0       1.0   
UNRATE                                        3.8       4.9       5.7   
CPIAUCSL                                    164.7     183.1     212.5   
rGDP                                         -8.4       0.9       2.2   
TCMR                                          1.5       2.3       3.7   
POILWTIUSDM                                  12.0      30.7      48.7   
TTLCONS                                 708,818.0 846,777.0 891,264.0   
DEXUSEU                                       0.9       1.1       1.2   
BOPGSTB                                 -67,823.0 -45,943.0 -41,360.0   
GOLDAMGBD228NLBM                            256.2     350.8     857.7   
CSUSHPISA                                    93.2     130.2     145.6   
MSPUS                                   157,400.0 190,100.0 224,100.0   

                                                75%         max  
Original_Interest_Rate                          6.1        11.0  
Original_UPB                              247,000.0 1,170,000.0  
Original_Loan_Term                            360.0       360.0  
Original_LTV_(OLTV)                            80.0        97.0  
Original_Combined_LTV_(CLTV)                   80.0       142.

In [45]:
fannie_mae.dropna()

Loan_Identifier Origination_Channel             Seller_Name  \
32     581,781,000,000.0                   R                   OTHER   
43     187,050,000,000.0                   B  WELLS FARGO BANK, N.A.   
44     799,435,000,000.0                   R          PNC BANK, N.A.   
75     375,704,000,000.0                   B            AMTRUST BANK   
87     635,398,000,000.0                   R          PNC BANK, N.A.   
...                  ...                 ...                     ...   
135020 492,288,000,000.0                   R                   OTHER   
135022 261,034,000,000.0                   R                   OTHER   
135025 715,384,000,000.0                   R                   OTHER   
135027 341,332,000,000.0                   R                   OTHER   
135031 114,990,000,000.0                   R                   OTHER   

        Original_Interest_Rate  Original_UPB  Original_Loan_Term  \
32                         6.0     337,000.0               360.0   
43                         6.5     194,000.0               360.0   
44                         6.6     155,000.0               240.0   
75                         6.6      61,000.0               360.0   
87                         6.0     318,000.0               360.0   
...                        ...           ...                 ...   
135020                     5.8     128,000.0               360.0   
135022                     4.8     185,000.0               360.0   
135025                     4.8     372,000.0               360.0   
135027                     5.2     269,000.0               360.0   
135031                     4.9     344,000.0               360.0   

        Original_LTV_(OLTV)  Original_Combined_LTV_(CLTV)  \
32                     95.0                          95.0   
43                     85.0                          85.0   
44                     82.0                          82.0   
75                     84.0                          84.0   
87                     90.0                          90.0   
...                     ...                           ...   
135020                 85.0                          85.0   
135022                 95.0                          95.0   
135025                 90.0                          90.0   
135027                 97.0                          97.0   
135031                 97.0                          97.0   

        Number_of_Borrowers  Original_Debt_to_Income_Ratio  ...  rGDP TCMR  \
32                      2.0                           48.0  ...   0.9  4.7   
43                      2.0                           52.0  ...   0.9  4.7   
44                      2.0                           50.0  ...   0.9  4.7   
75                      2.0                           31.0  ...   0.9  4.7   
87                      2.0                           47.0  ...   0.9  4.7   
...                     ...                            ...  ...   ...  ...   
135020                  2.0                           45.0  ...   3.5  2.9   
135022                  2.0                           48.0  ...   3.5  2.9   
135025                  2.0                           37.0  ...   3.5  2.9   
135027                  2.0                           46.0  ...   3.5  2.9   
135031                  2.0                           42.0  ...   3.5  2.9   

       POILWTIUSDM     TTLCONS DEXUSEU   BOPGSTB  GOLDAMGBD228NLBM  CSUSHPISA  \
32            59.3 1,138,752.0     1.3 -58,478.0             665.1      184.6   
43            59.3 1,138,752.0     1.3 -58,478.0             665.1      184.6   
44            59.3 1,138,752.0     1.3 -58,478.0             665.1      184.6   
75            59.3 1,138,752.0     1.3 -58,478.0             665.1      184.6   
87            59.3 1,138,752.0     1.3 -58,478.0             665.1      184.6   
...            ...         ...     ...       ...               ...        ...   
135020        67.5 1,317,790.0     1.2 -47,431.0           1,299.2      202.4   
135022   

In [37]:
fannie_mae['1_coscore'] = np.log(fannie_mae['Co-borrower_credit_score_at_origination'])

In [43]:
sm_ols('Original_Interest_Rate ~ 1_coscore', data = fannie_mae).fit().summary()

SyntaxError: invalid syntax (<unknown>, line 1)

In [42]:
#if i'm willing to assume that all missing credit scores are avg:
mean_coscore = fannie_mae['1_coscore'].mean()
fannie_mae['1_coscore'] = fannie_mae['1_coscore'].fillna(mean_coscore)

TypeError: can only concatenate str (not "float") to str

In [40]:
fannie_mae['1_coscore'].describe()

count     135038
unique       328
top         mean
freq       67672
Name: 1_coscore, dtype: object

In [60]:
from sklearn import preprocessing
fannie_mae = fannie_mae.dropna(subset = ['Origination_Channel'])
X_train = np.array(fannie_mae)
X_scaled = preprocessing.scale(X_train)

#print(' X_scaled\n',         '-'*40,'\n',X_scaled,'\n')
#print(' Mean of each var:\n','-'*40,'\n',X_scaled.mean(axis=0),'\n')
#print(' STD of each var:\n', '-'*40,'\n',X_scaled.std(axis=0),'\n')

ValueError: could not convert string to float: 'B'